name: "FAP: Build and lint"
on: [push, pull_request]
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: 'ufbt: Build for Release branch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build mfc-editor with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          task: build
          app-dir: "mfc-editor"
          ufbt-args: ""
          sdk-channel: release
      - name: Upload mfc-editor artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-mfc-editor-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          # skip SDK setup, we already did it in previous step
          skip-setup: true
          task: lint
