name: Lint Code

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: flipperzero-lightmeter
        submodules: 'true'
        
    - name: Lint
      uses: oleksiikutuzov/flipperzero-ufbt-action@lint
      with:
        fap-dir: flipperzero-lightmeter
        lint: true

