name: "PR - Lint & build."
on: pull_request
jobs:
  ufbt-test-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "dev"
            sdk-channel: dev

          - name: "rc"
            sdk-channel: rc

          - name: "release"
            sdk-channel: release

    name: "PR Build: ${{ matrix.name }}."
    steps:
      - name: "PR - Checkout."
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Flipper Zero ufbt action
      # https://github.com/flipperdevices/flipperzero-ufbt-action
      - name: "PR - Build app."
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          app-dir: ./fap
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: "PR - Lint."
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          app-dir: ./fap
          skip-setup: true
          task: lint
